version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: food-mysql
    restart: always
    environment:
      DB_URL: jdbc:mysql://mysql:3306/fooddb
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: fooddb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: food-redis
    ports:
      - "6379:6379"

  backend:
    build: .
    container_name: food-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SECRET_JWT_STRING: foodAppDevSecretKey1234567890!@#
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USERNAME: mustafaguler4@gmail.com
      MAIL_PASSWORD: 05377048490mus
      BASE_PAYMENT_LINK: http://localhost:3000/pay?orderid=
      FRONTEND_BASE_URL: http://localhost:3000
      STRIPE_PUBLIC_KEY: pk_test_...
      STRIPE_SECRET_KEY: sk_test_...
    depends_on:
      - mysql
      - redis

volumes:
  mysql_data: