version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: food-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: fooddb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: food-redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: food-backend
    ports:
      - "8080:8080"
    env_file:
      - .env.dev
    depends_on:
      - mysql
      - redis
  prometheus:
    image: prom/prometheus
    container_name: food-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: food-grafana
    ports:
      - "3001:3000"

volumes:
  mysql_data: