version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: food-mysql
    restart: always
    environment:
      DB_URL: jdbc:mysql://mysql:3306/fooddb
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: fooddb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: food-redis
    ports:
      - "6379:6379"

  backend:
    build: .
    container_name: food-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      BASE_PAYMENT_LINK: ${BASE_PAYMENT_LINK}
      FRONTEND_BASE_URL: ${FRONTEND_BASE_URL}
      STRIPE_PUBLIC_KEY: ${STRIPE_PUBLIC_KEY}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
    env_file:
      - .env.dev.dev
    depends_on:
      - mysql
      - redis

volumes:
  mysql_data: