server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

base:
  payment:
    link: ${BASE_PAYMENT_LINK}

frontend:
  base:
    url: ${FRONTEND_BASE_URL}

stripe:
  api:
    public-key: ${STRIPE_PUBLIC_KEY}
    secret-key: ${STRIPE_SECRET_KEY}

secretJwtString: ${JWT_SECRET}